services:
  - type: web
    name: codesentinel-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: codesentinel-db
          property: connectionString

databases:
  - name: codesentinel-db
    databaseName: codesentinel
    user: codesentinel
