# Generated by Django 4.2.11 on 2026-07-05 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_id_slug', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(default='python', max_length=50)),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=1000)),
                ('line_start', models.IntegerField()),
                ('line_end', models.IntegerField()),
                ('column_start', models.IntegerField(blank=True, null=True)),
                ('column_end', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('fix_suggestion', models.TextField()),
                ('code_snippet', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('source', models.CharField(max_length=20)),
                ('owasp_category', models.CharField(blank=True, max_length=100)),
                ('cwe_id', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('suppressed', 'Suppressed'), ('false_positive', 'False Positive')], db_index=True, default='open', max_length=20)),
                ('suppressed_reason', models.TextField(blank=True)),
                ('suppressed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='findings', to='findings.rule')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan')),
                ('suppressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressed_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'db_table': 'findings',
                'ordering': ['-severity', '-confidence_score'],
                'indexes': [models.Index(fields=['scan', 'severity'], name='findings_scan_id_8f361b_idx'), models.Index(fields=['scan', 'status'], name='findings_scan_id_1b4006_idx')],
            },
        ),
    ]
