# Generated by Django 4.2.11 on 2026-07-05 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commit_sha', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning Repository'), ('analyzing', 'Analyzing Files'), ('running_ml', 'Running ML Detection'), ('aggregating', 'Aggregating Results'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('total_findings', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('lines_of_code', models.IntegerField(default=0)),
                ('files_scanned', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='repositories.repository')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scan',
                'verbose_name_plural': 'Scans',
                'db_table': 'scans',
                'ordering': ['-started_at'],
            },
        ),
    ]
